import fs from 'node:fs';import path from 'node:path';import {createRequire} from 'node:module';import {pathToFileURL} from 'node:url';import http from 'node:http';
import {root,auditDir,isolatedEnv} from './audit-env.mjs';
const fx=JSON.parse(fs.readFileSync(path.join(auditDir,'local-fixture.json')));Object.assign(process.env,isolatedEnv(),{MONGODB_URI:fx.uri});const require=createRequire(path.join(root,'server/package.json'));const mongoose=require('mongoose'),jwt=require('jsonwebtoken');await mongoose.connect(fx.uri);
const mod=async p=>import(pathToFileURL(path.join(root,'server/src',p)));const out=[];let n=0;const tokens=Object.fromEntries(Object.entries(fx.users).map(([r,u])=>[r,jwt.sign({sub:u.id,tokenVersion:0},process.env.JWT_ACCESS_SECRET,{expiresIn:'2h'})]));
async function req(name,method,url,role,body){const t=performance.now();const r=await fetch('http://127.0.0.1:5015'+url,{method,headers:{Authorization:'Bearer '+tokens[role],'Content-Type':'application/json','X-Forwarded-For':'198.19.50.'+(++n)},body:body===undefined?undefined:JSON.stringify(body),signal:AbortSignal.timeout(15000)});let data=await r.json();out.push({name,status:r.status,ms:Math.round(performance.now()-t),data});return data.data;}
await req('payslips-missing-route','GET','/api/me/payslips','Worker');
const Timesheet=(await mod('modules/timesheets/timesheet.model.js')).default;const ts=await Timesheet.findOne({employee:fx.users.Worker.employee});await req('admin-timesheet-approved','PATCH','/api/timesheets/'+ts._id+'/decide','Admin',{status:'Approved'});
const lt=await req('date-test-policy','POST','/api/leave-types','Admin',{name:'QA timestamp manual',recurrence:'Manual'});
await req('two-calendar-dates-counted-one','POST','/api/me/leave','Worker',{leaveType:lt._id,startDate:'2026-10-20T23:59:00Z',endDate:'2026-10-21T00:01:00Z'});
const annual=await req('annual-test-policy','POST','/api/leave-types','Admin',{name:'QA yearly boundaries',recurrence:'Annual',daysPerYear:2});
await req('future-leave-2027','POST','/api/me/leave','Staff',{leaveType:annual._id,startDate:'2027-06-01',endDate:'2027-06-02'});
await req('future-leave-2028','POST','/api/me/leave','Staff',{leaveType:annual._id,startDate:'2028-06-01',endDate:'2028-06-02'});
const Outsourced=(await mod('modules/employees/outsourcedEmployee.model.js')).default;
await Outsourced.insertMany(Array.from({length:1200},(_,i)=>({name:'Synthetic load '+String(i).padStart(4,'0'),workerType:'Freelancer',createdBy:fx.users.Admin.id,iqamaNumber:'QA'+i,documents:[]})));
const list=await req('unbounded-outsourced-list','GET','/api/outsourced-employees?limit=1000000','Worker');out.at(-1).data={returnedRecords:list.length};
const stats=await Outsourced.find({name:{$regex:'Synthetic',$options:'i'}}).sort({name:1}).limit(100).explain('executionStats');out.push({name:'outsourced-search-explain',nReturned:stats.executionStats.nReturned,totalDocsExamined:stats.executionStats.totalDocsExamined,totalKeysExamined:stats.executionStats.totalKeysExamined,executionTimeMillis:stats.executionStats.executionTimeMillis});
// Exercise the actual Express app/controller with only the external CDN fetch stubbed.
const {default:app}=await mod('app.js');const server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));const originalFetch=globalThis.fetch;let signedTarget=null;globalThis.fetch=async(input,opts)=>{if(String(input).startsWith('https://res.cloudinary.com/audit-disabled/')){signedTarget=new URL(String(input)).hostname;return new Response('PRIVATE SYNTHETIC FILE CONTENT',{status:200});}return originalFetch(input,opts)};
const download=await originalFetch('http://127.0.0.1:'+server.address().port+'/api/outsourced-employees/'+fx.outsourced+'/documents/'+fx.outsourcedFile+'/file',{headers:{Authorization:'Bearer '+tokens.Worker}});out.push({name:'worker-private-file-inprocess-cdn-stub',status:download.status,body:await download.text(),signedTarget});globalThis.fetch=originalFetch;server.close();
// Source-identical Axios module, replacing only its Vite constant import for a local hanging fixture.
const hang=http.createServer((_req,_res)=>{});await new Promise(r=>hang.listen(0,'127.0.0.1',r));const src=fs.readFileSync(path.join(root,'client/src/lib/axios.js'),'utf8').replace("import axios from 'axios';",`import axios from '${pathToFileURL(path.join(root,'client/node_modules/axios/index.js')).href}';`).replace("import { API_URL } from './constants.js';",`const API_URL='http://127.0.0.1:${hang.address().port}';`);const ax=await import('data:text/javascript;base64,'+Buffer.from(src).toString('base64'));const abort=new AbortController();let state='pending';const pending=ax.api.get('/auth/refresh',{signal:abort.signal}).then(()=>state='fulfilled',()=>state='rejected');await new Promise(r=>setTimeout(r,1200));out.push({name:'axios-no-timeout',timeout:ax.api.defaults.timeout,stateAfter1200ms:state});abort.abort();await pending;hang.closeAllConnections();hang.close();
fs.writeFileSync(path.join(auditDir,'deep-evidence.json'),JSON.stringify(out,null,2));console.log(JSON.stringify(out.map(x=>({...x,data:x.name==='two-calendar-dates-counted-one'?x.data:x.data?.message??x.data})),null,2));await mongoose.disconnect();process.exit();
