import fs from 'node:fs';import path from 'node:path';import {createRequire} from 'node:module';import {pathToFileURL} from 'node:url';import {root,auditDir,isolatedEnv} from './audit-env.mjs';
const fx=JSON.parse(fs.readFileSync(path.join(auditDir,'local-fixture.json')));Object.assign(process.env,isolatedEnv(),{MONGODB_URI:fx.uri});const require=createRequire(path.join(root,'server/package.json'));const mongoose=require('mongoose'),jwt=require('jsonwebtoken');await mongoose.connect(fx.uri);const mod=async p=>import(pathToFileURL(path.join(root,'server/src',p)));const tokens=Object.fromEntries(Object.entries(fx.users).map(([r,u])=>[r,jwt.sign({sub:u.id,tokenVersion:0},process.env.JWT_ACCESS_SECRET,{expiresIn:'2h'})]));const out=[];
async function req(name,url,role){const r=await fetch('http://127.0.0.1:5015'+url,{headers:{Authorization:'Bearer '+tokens[role],'X-Forwarded-For':'198.19.150.1'},signal:AbortSignal.timeout(10000)});const data=await r.json();out.push({name,status:r.status,data});return data.data;}
await req('invalid-regex-filter','/api/deployments?site=%5B','Admin');
const Mob=(await mod('modules/mobilisations/mobilisation.model.js')).default;const mob=await Mob.findOne({serialNumber:'MOB-0001'});await Mob.updateOne({_id:mob._id},{$push:{coordinators:{user:fx.users.CoordinatorB.id,isPrimary:false,confirmed:true}}});
const ds=await req('joint-coordinator-deployments-list','/api/deployments','CoordinatorB');const dep=ds.items.find(x=>String(x.mobilisation._id)===String(mob._id));out.at(-1).data={listed:!!dep,deploymentId:dep?._id};if(dep)await req('joint-coordinator-detail-rejected','/api/deployments/'+dep._id,'CoordinatorB');
const service=await mod('modules/mobilisationTargets/mobilisationTarget.service.js');await Promise.all(Object.values(mongoose.models).map(m=>m.init()));const calls=[];mongoose.set('debug',(c,m)=>calls.push(c+'.'+m));const t=performance.now();await service.getAllMonthlyProgressWindow({userId:fx.users.Admin.id,role:'Admin'},'2026-10');mongoose.set('debug',false);out.push({name:'warm-target-query-count',dbCalls:calls.length,ms:Math.round(performance.now()-t),callsByType:Object.fromEntries([...new Set(calls)].map(c=>[c,calls.filter(x=>x===c).length]))});
// Document why these exports are candidates, separating locally-used helpers from dead functions.
const espree=require('espree');const stat=JSON.parse(fs.readFileSync(path.join(auditDir,'static-evidence.json')));const dead=[];for(const e of stat.unusedExportCandidates){const tree=espree.parse(fs.readFileSync(path.join(root,e.file),'utf8'),{ecmaVersion:'latest',sourceType:'module',ecmaFeatures:{jsx:true}});let count=0;function walk(n){if(!n||typeof n!=='object')return;if(n.type==='Identifier'&&n.name===e.name)count++;for(const v of Object.values(n)){if(Array.isArray(v))v.forEach(walk);else if(v&&typeof v==='object')walk(v)}}walk(tree);dead.push({...e,identifierOccurrencesInOwnModule:count,classification:count===1?'No code references found':'Locally used; only export appears redundant'});}fs.writeFileSync(path.join(auditDir,'dead-export-candidates.json'),JSON.stringify(dead,null,2));
fs.writeFileSync(path.join(auditDir,'final-probes.json'),JSON.stringify(out,null,2));console.log(JSON.stringify(out,null,2));await mongoose.disconnect();process.exit();
