import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import {createRequire} from 'node:module';import {execFileSync} from 'node:child_process';import {root,auditDir} from './audit-env.mjs';
const require=createRequire(path.join(root,'server/package.json')),espree=require('espree');const read=p=>fs.readFileSync(path.join(root,p),'utf8');const parse=s=>espree.parse(s,{ecmaVersion:'latest',sourceType:'module',range:true,loc:true,ecmaFeatures:{jsx:true}});
function walk(n,cb){if(!n||typeof n!=='object')return;if(n.type)cb(n);for(const[k,v]of Object.entries(n)){if(['loc','range'].includes(k))continue;if(Array.isArray(v))v.forEach(x=>walk(x,cb));else if(v&&typeof v==='object')walk(v,cb);}}
function files(d){return fs.readdirSync(path.join(root,d),{withFileTypes:true}).flatMap(x=>x.isDirectory()?files(d+'/'+x.name):[d+'/'+x.name]);}
const sources=Object.fromEntries([...files('server/src'),...files('client/src'),...files('mcp-server').filter(x=>!x.includes('node_modules/'))].filter(f=>/\.(m?js|jsx|cjs)$/.test(f)&&!f.includes('node_modules/')).map(f=>[f,read(f)]));const duplicates=new Map(),exports=[],errors=[],keys=[];
for(const[f,s]of Object.entries(sources)){let ast;try{ast=parse(s)}catch(e){errors.push({file:f,message:e.message});continue;}walk(ast,n=>{if(/FunctionDeclaration|ArrowFunctionExpression|FunctionExpression/.test(n.type)&&n.body?.type==='BlockStatement'){const body=s.slice(...n.body.range);const token=espree.tokenize(body,{ecmaVersion:'latest',ecmaFeatures:{jsx:true}}).map(t=>t.value).join(' ');if(token.length>180){const hash=crypto.createHash('sha256').update(token).digest('hex');const arr=duplicates.get(hash)??[];arr.push({file:f,line:n.loc.start.line,name:n.id?.name??'(anonymous)',length:token.length});duplicates.set(hash,arr);}}
if(n.type==='ExportNamedDeclaration'&&n.declaration){const d=n.declaration;if(d.id?.name)exports.push({file:f,line:d.loc.start.line,name:d.id.name});if(d.declarations)for(const v of d.declarations)if(v.id.type==='Identifier')exports.push({file:f,line:v.loc.start.line,name:v.id.name});}
if(n.type==='CallExpression'&&['requireSectionAccess','canAccessSection','guarded','guardedWrite','canReadSection','canWriteSection'].includes(n.callee.name)&&typeof n.arguments[0]?.value==='string')keys.push({file:f,line:n.loc.start.line,call:n.callee.name,key:n.arguments[0].value,level:n.arguments[1]?.value});});}
const candidates=exports.filter(e=>!Object.entries(sources).some(([f,s])=>f!==e.file&&new RegExp('\\b'+e.name+'\\b').test(s)));
const model=parse(read('server/src/modules/sectionAccess/sectionAccess.model.js'));let serverKeys=[];walk(model,n=>{if(n.type==='VariableDeclarator'&&n.id.name==='SECTION_KEYS')serverKeys=n.init.elements.map(x=>x.value);});
const groupKeys=[...read('client/src/features/sectionAccess/sectionAccessModules.js').matchAll(/sectionKeys:\s*\[([^\]]*)\]/g)].flatMap(m=>[...m[1].matchAll(/'([^']+)'/g)].map(x=>x[1]));
const secretPatterns=[['private-key',/-----BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY-----/g],['aws-key',/AKIA[0-9A-Z]{16}/g],['github-token',/(?:ghp_[A-Za-z0-9]{30,}|github_pat_[A-Za-z0-9_]{40,})/g],['stripe-secret',/sk_live_[A-Za-z0-9]{20,}/g],['credential-mongo-uri',/mongodb(?:\+srv)?:\/\/[^\s:'"]+:[^\s@'"]+@/g]];
const secrets=[];const repo=[];for(const dir of ['server','client']){const git=(a)=>execFileSync('git',['-C',path.join(root,dir),...a],{encoding:'utf8',maxBuffer:150*1024*1024});const tracked=git(['ls-files']).trim().split('\n');repo.push({dir,head:git(['rev-parse','HEAD']).trim(),commits:Number(git(['rev-list','--count','HEAD'])),tracked:tracked.length,status:git(['status','--short'])});for(const f of tracked){if(!/\.(?:[cm]?jsx?|json|md|ya?ml|env|example|txt|properties|gradle|xml)$|(?:^|\/)\.env/.test(f))continue;let s;try{s=read(dir+'/'+f)}catch{continue;}for(const[type,re]of secretPatterns){re.lastIndex=0;for(const m of s.matchAll(re)){secrets.push({scope:'working-tree',file:dir+'/'+f,line:s.slice(0,m.index).split('\n').length,type,placeholder:/user:password|username:password|<|example|your[-_]/i.test(m[0])});}}}
const history=git(['log','--all','--format=COMMIT:%H','-p','--no-ext-diff','--','.',' :(exclude)package-lock.json'.trim()]);let commit='',file='';for(const line of history.split('\n')){if(line.startsWith('COMMIT:'))commit=line.slice(7);if(line.startsWith('+++ b/'))file=line.slice(6);if(!line.startsWith('+')||line.startsWith('+++'))continue;for(const[type,re]of secretPatterns){re.lastIndex=0;const m=re.exec(line);if(m)secrets.push({scope:'history',file:dir+'/'+file,commit,type,placeholder:/user:password|username:password|<|example|your[-_]/i.test(m[0])});}}
}
const result={repos:repo,parsedFiles:Object.keys(sources).length,parseErrors:errors,duplicateFunctions:[...duplicates.values()].filter(a=>a.length>1).sort((a,b)=>b[0].length-a[0].length),unusedExportCandidates:candidates,sectionAccess:{serverKeys,groupKeys,missingInClientGroups:serverKeys.filter(x=>!groupKeys.includes(x)),unknownClientGroupKeys:groupKeys.filter(x=>!serverKeys.includes(x)),invalidCalls:keys.filter(x=>!serverKeys.includes(x.key)),calls:keys},secretCandidates:secrets};fs.writeFileSync(path.join(auditDir,'static-evidence.json'),JSON.stringify(result,null,2));console.log(JSON.stringify({...result,duplicateFunctions:result.duplicateFunctions.slice(0,12),sectionAccess:{...result.sectionAccess,calls:undefined},secretCandidates:secrets.slice(0,20)},null,2));
