import fs from 'node:fs';import path from 'node:path';import {createRequire} from 'node:module';import {pathToFileURL} from 'node:url';
import {root,auditDir,isolatedEnv} from './audit-env.mjs';
const fx=JSON.parse(fs.readFileSync(path.join(auditDir,'local-fixture.json')));Object.assign(process.env,isolatedEnv(),{MONGODB_URI:fx.uri});
const require=createRequire(path.join(root,'server/package.json'));const mongoose=require('mongoose'),jwt=require('jsonwebtoken');await mongoose.connect(fx.uri);
const mod=async p=>import(pathToFileURL(path.join(root,'server/src',p)));const ApprovalRole=(await mod('modules/approvals/approvalRole.model.js')).default;const sec=await mod('modules/sectionAccess/sectionAccess.model.js');
const grant=await ApprovalRole.create({name:'Isolated QA grant 2',members:[fx.users.Coordinator.id,fx.users.CoordinatorB.id]});
for(const key of sec.SECTION_KEYS)await sec.default.updateOne({sectionKey:key},{$set:{readApprovalRoles:[grant._id],writeApprovalRoles:[grant._id]}},{upsert:true});
const tokens=Object.fromEntries(Object.entries(fx.users).map(([r,u])=>[r,jwt.sign({sub:u.id,tokenVersion:0},process.env.JWT_ACCESS_SECRET,{expiresIn:'2h'})]));let n=0;const out=[];
async function req(name,method,url,role,body,ip){const r=await fetch('http://127.0.0.1:5015'+url,{method,headers:{Authorization:'Bearer '+tokens[role],'Content-Type':'application/json','X-Forwarded-For':ip??'198.19.'+Math.floor(n++/200)+'.2'},body:body===undefined?undefined:JSON.stringify(body),signal:AbortSignal.timeout(15000)});const text=await r.text();let data;try{data=JSON.parse(text)}catch{data=text.slice(0,200)};const e={name,method,url,role,status:r.status,data};out.push(e);if(name!=='rate-budget')console.log(JSON.stringify(e));return e;}
await req('coordinator-own-employee','GET','/api/employees/'+fx.users.Worker.employee,'Coordinator');
await req('coordinator-foreign-employee','GET','/api/employees/'+fx.users.Staff.employee,'Coordinator');
await req('coordinator-foreign-document','GET','/api/documents/'+fx.foreignDocument+'/file','Coordinator');
const lt=await req('manual-leave-type-create','POST','/api/leave-types','Admin',{name:'Isolated Manual QA',recurrence:'Manual'});
if(lt.data.data?._id){const lid=lt.data.data._id;const leave=await req('worker-leave-submit','POST','/api/me/leave','Worker',{leaveType:lid,startDate:'2026-11-01',endDate:'2026-11-02'});if(leave.data.data?._id){await req('foreign-coordinator-leave-decision','PATCH','/api/leave/'+leave.data.data._id+'/decide','CoordinatorB',{status:'Approved'});await req('own-coordinator-leave-decision','PATCH','/api/leave/'+leave.data.data._id+'/decide','Coordinator',{status:'Approved'});await req('other-worker-cancel','PATCH','/api/me/leave/'+leave.data.data._id+'/cancel','Staff');}
await req('invalid-leave-type-change','PATCH','/api/leave-types/'+lid,'Admin',{recurrence:'Sick'});
await req('submit-malformed-sick-policy','POST','/api/me/leave','Worker',{leaveType:lid,startDate:'2026-12-01',endDate:'2026-12-02'});}
const ts=await req('worker-timesheet-submit','POST','/api/me/timesheets','Worker',{periodStart:'2026-09-20'});if(ts.data.data?._id){await req('foreign-timesheet-decision','PATCH','/api/timesheets/'+ts.data.data._id+'/decide','CoordinatorB',{status:'Approved'});await req('own-timesheet-decision','PATCH','/api/timesheets/'+ts.data.data._id+'/decide','Coordinator',{status:'Approved'});await req('duplicate-timesheet','POST','/api/me/timesheets','Worker',{periodStart:'2026-09-20'});}
const mob=await req('mobilisation-create','POST','/api/mobilisations','Admin',{workerType:'Employee',worker:fx.users.Worker.employee,jobTitle:'QA test',client:fx.client,clientRate:25,requiredTimesheetHours:200,otClientRate:30,otEmployeeRate:20,mobilisationDate:'2026-09-01'});
if(mob.data.data?._id){const mid=mob.data.data._id;await req('mobilisation-submit','POST','/api/mobilisations/'+mid+'/submit','Admin');await req('mobilisation-approve','PATCH','/api/mobilisations/'+mid+'/decide','Admin',{status:'Approved'});const list=await req('deployments-list','GET','/api/deployments','Admin');const items=list.data.data?.items??list.data.data;const dep=Array.isArray(items)?items.find(x=>String(x.mobilisation?._id??x.mobilisation)===mid):null;if(dep){await req('impossible-month-hours','POST','/api/deployments/'+dep._id+'/monthly-hours','Admin',{month:'2026-09',actualHours:900});await Promise.all([req('concurrent-hours-a','POST','/api/deployments/'+dep._id+'/monthly-hours','Admin',{month:'2026-09',actualHours:220}),req('concurrent-hours-b','POST','/api/deployments/'+dep._id+'/monthly-hours','Admin',{month:'2026-09',actualHours:220})]);await req('foreign-deployment-read','GET','/api/deployments/'+dep._id,'CoordinatorB');}}
let first429=null;for(let i=1;i<=602;i++){const r=await req('rate-budget','GET','/api/notifications/unread-count',['Manager','HR','Accounts'][i%3],undefined,'198.19.250.250');if(r.status===429&&!first429)first429=i;}console.log('RATE_FIRST_429',first429);
fs.writeFileSync(path.join(auditDir,'workflow-evidence.json'),JSON.stringify({checks:out.filter(x=>x.name!=='rate-budget'),rate:{total:602,first429,roleRequests:201}},null,2));await mongoose.disconnect();

